// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-w0ls446vs5Ja3d7Itgk_sycbAweKCCA',
    appId: '1:701033692341:web:9556b9f8584f85671ed2fc',
    messagingSenderId: '701033692341',
    projectId: 'amipet-c9144',
    authDomain: 'amipet-c9144.firebaseapp.com',
    storageBucket: 'amipet-c9144.firebasestorage.app',
    measurementId: 'G-QDYKDB4LDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtIMJ6yrtJz7AKIIxu97nV5yZYaPqsMVU',
    appId: '1:701033692341:android:52814f28a79809bf1ed2fc',
    messagingSenderId: '701033692341',
    projectId: 'amipet-c9144',
    storageBucket: 'amipet-c9144.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYLu-rmEDRqjq00ITDLkfhYdI0H657KJ0',
    appId: '1:701033692341:ios:5d0ef563458b9d541ed2fc',
    messagingSenderId: '701033692341',
    projectId: 'amipet-c9144',
    storageBucket: 'amipet-c9144.firebasestorage.app',
    androidClientId: '701033692341-pdrgr326gr2qphe4i90ckj8u7phkk3fm.apps.googleusercontent.com',
    iosClientId: '701033692341-6rdhlo1f5v0bjfdvqdr2u13tp327j43g.apps.googleusercontent.com',
    iosBundleId: 'com.example.amipet',
  );
}
